### ISSUE TITLE
[DOCS] ENV Setting

### ISSUE THREAD

**Issue by pintordev** [pintordev/rps#4]
## 📌 DB 환경 구축 / 앱 설정
```yaml
version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env/db/.env
    volumes:
      - ./.env/db/data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
```

## 📝 내용
- 개발에 필요한 DB 환경 우선 구축
- .gitignore에 env_file 지정 경로 및 앱 설정 파일 추가 -> github 업로드 방지
- 앱 실행해서 docker에 띄워둔 db와 연결 상태 확인 완료
- 추후 앱 관련 내용 docker-compose.yml 파일에 추가 예정
